### ISSUE TITLE
error in : Identified heterozygous SNPs in short read VCF

### ISSUE THREAD

**Issue by Lcornet** [nPhasePipeline/nPhase#4]
I installed phase in a singularity container (actually I installed the condo in the container).
I have an issue while running nphase and I am not sure if it's a problem due to the container or to nphase itself :

Long reads successfully mapped to reference
Removing quality 0 (multimapped) reads, turning to bam and sorting it
Short reads successfully mapped to reference
Identified heterozygous SNPs in short read VCF
Traceback (most recent call last):
  File "/opt/miniconda/bin/nphase", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 298, in main
    nPhasePipeline(args)
  File "/opt/miniconda/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 140, in nPhasePipeline
    line=[line[0],str(int(line[1])-1),line[1]]
ValueError: invalid literal for int() with base 10: '62166_obj'

Can you help me ?

**Comment by nPhasePipeline** [comment]
It looks like there's a problem with the vcf. Did you use the full pipeline or did you run the partial one?

Either way can you look into your output folder and attach the vcf file that should be in VariantCalls/shortReads/*.vcf so I can look into what went wrong?

**Comment by Lcornet** [comment]
The full one, this is my command:

singularity exec --bind /globalscratch/lcornet/nphase:/mnt nphase.sif nphase pipeline --sampleName TME3 --reference /mnt/tme-hybrid-complete.fasta --R1 /mnt/separator-R1.paired.fastq --R2 /mnt/separator-R2.paired.fastq --longReads /mnt/tme3_all_cells_more_than_8_kb.fastq --longReadPlatform ont --output /mnt/NPHASE --threads 20

I can join the VCF file but too big for Git, 30 mb after compressed. What do you suggest ?

Thanks for the help

**Comment by nPhasePipeline** [comment]
I think the first 1000 or 10 000 lines should be enough for me to see the source of the error.

To be more precise you could send me a file that contains the output of

`cat ${yourVCF} | grep -v "#" | grep -v "AF=1.00" | head -n 1000 >debug.txt`

**Comment by Lcornet** [comment]
[debug.zip](https://github.com/nPhasePipeline/nPhase/files/5333132/debug.zip)

This a head of the 3 VCF files.

**Comment by Lcornet** [comment]
[debug.zip](https://github.com/nPhasePipeline/nPhase/files/5333132/debug.zip)

This a head of the 3 VCF files.

**Comment by nPhasePipeline** [comment]
It looks fine. Can you check if any of these vcf files have an output when you do a

`grep 62166_obj`

Essentially the error is that, in the hetSNPs.vcf file, it expects the second column to be the position, which will be a number. But in one of the lines, the second column says "62166_obj" instead. I'm not sure what could cause that to happen. Maybe once we find that line it'll make more sense.

**Comment by Lcornet** [comment]
Yes the grep cmd gives a lot of line in output for each VCF file:

$grep 62166_obj  TME3.vcf | head -n3
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166>
contig_491_pilon_subseq_1:62166_obj	120	.	GT	G	52.28	.	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=40.00;QD=26.14;SOR=2.303	GT:AD:DP:GQ:PL	1/1:0,2:2:6:64,6,0
contig_491_pilon_subseq_1:62166_obj	249	.	CA	C	228.93	.	AC=2;AF=1.00;AN=2;DP=6;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=38.14;QD=35.09;SOR=3.912	GT:AD:DP:GQ:PL	1/1:0,6:6:18:243,18,0

$grep 62166_obj  TME3.SNPs.vcf | head -n3
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166,assembly=tme-hybrid-complete.fasta>
contig_491_pilon_subseq_1:62166_obj	520	.	T	A	221.64	.	AC=1;AF=0.500;AN=2;BaseQRankSum=1.163;DP=34;ExcessHet=3.0103;FS=11.553;MLEAC=1;MLEAF=0.500;MQ=42.84;MQRankSum=0.184;QD=6.93;ReadPosRankSum=-1.874;SOR=3.486	GT:AD:DP:GQ:PL	0/1:24,8:32:99:229,0,930
contig_491_pilon_subseq_1:62166_obj	632	.	G	A	116.64	.	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.287;DP=33;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=40.39;MQRankSum=-2.299;QD=3.89;ReadPosRankSum=0.078;SOR=0.735	GT:AD:DP:GQ:PL	0/1:24,6:30:99:124,0,817

$ grep 62166_obj TME3.hetSNPs.vcf | head -n3
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166,assembly=tme-hybrid-complete.fasta>
contig_491_pilon_subseq_1:62166_obj	520	.	T	A	221.64	.	AC=1
contig_491_pilon_subseq_1:62166_obj	632	.	G	A	116.64	.	AC=1


I tried to find 62166_obj in the second column (in coordinates) without success (got in defline) :
$ grep 62166_obj  TME3.SNPs.vcf | cut -f2 | grep 62166_obj
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166,assembly=tme-hybrid-complete.fasta>
$ grep 62166_obj  TME3.vcf | cut -f2 | grep 62166_obj
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166>
$ grep 62166_obj  TME3.hetSNPs.vcf | cut -f2 | grep 62166_obj
##contig=<ID=contig_491_pilon_subseq_1:62166_obj,length=62166,assembly=tme-hybrid-complete.fasta>

**Comment by nPhasePipeline** [comment]
Okay, I found the error. Part of my code splits the name of your contig because there's a ":" in it. Was that contig name automatically generated by a program?

For a quick fix that you can do now, you can rename the headers of your reference file to replace the ":" by a "_", then start over with the same nphase pipeline command and it should work fine. If you have "=" in any header you should replace it with a "_" too, just to be safe.

So you would replace **contig_491_pilon_subseq_1:62166_obj** by **contig_491_pilon_subseq_1_62166_obj**

I'll fix this bug and upload a new version next week and then close this issue. Thanks for bringing it to my attention! Let me know if you run into any more trouble.

**Comment by Lcornet** [comment]
Yes all the names are generated by the programs Flye-pilon-bionano.

I'll try that, thanks.

**Comment by nPhasePipeline** [comment]
Should be fixed by v1.0.13
