### ISSUE TITLE
Short reads unsuccessfully mapped to reference

### ISSUE THREAD

**Issue by Lcornet** [nPhasePipeline/nPhase#5]
When I use the Conda installation, I got this error : 

Long reads successfully mapped to reference
Removing quality 0 (multimapped) reads, turning to bam and sorting it
ERROR: Short reads unsuccessfully mapped to reference

this is my command:

conda activate polyploidPhasing
nphase pipeline --sampleName TME3 --reference /media/vol2/scratch/lcornet/cassava/NPHASE/tme-hybrid-complete.fasta --R1 /media/vol2/scratch/lcornet/cassava/Dataset/raw-illumina/tme3/separator-R1.paired.fastq --R2 /media/vol2/scratch/lcornet/cassava/Dataset/raw-illumina/tme3/separator-R2.paired.fastq --longReads /media/vol2/scratch/lcornet/cassava/Dataset/ONT/tme3/tme3_all_cells_more_than_8_kb.fastq --longReadPlatform ont --output /media/vol2/scratch/lcornet/cassava/NPHASE/nphase --threads 40

The same command works (at this first step) with a singularity and the same file. Is there something more do to do with conda ? Can it be linked to a RAM problem ?

Thanks,

**Comment by nPhasePipeline** [comment]
Conda just installs everything into an environment, so I don't think it's to blame.

Do you get any error messages from GATK while running? Maybe in the log file?

It can be a RAM problem, yes, and if it is then GATK will give us an error to say so.

**Comment by Lcornet** [comment]
this the GATK part :  

Using GATK jar /media/vol2/home/lcornet/miniconda/envs/polyploidPhasing/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /media/vol2/home/lcornet/miniconda/envs/polyploidPhasing/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar MarkDuplicates --REMOVE_DUPLICATES true -I /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.bam -O /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam -M /dev/null


STDOUT:



COMMAND: samtools sort /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam -o /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.final.bam

STDERR:

[E::hts_open_format] Failed to open file /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam
samtools sort: can't open "/media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam": No such file or directory

**Comment by Lcornet** [comment]
and this the part just above GATK :  


STDOUT:



COMMAND: samtools view -bT /media/vol2/scratch/lcornet/cassava/NPHASE/tme-hybrid-complete.fasta -q 1 /media/vol2/scratch/lcornet/cassava/NPHASE/
nphase/TME3/Mapped/shortReads/TME3.sam -o /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.bam

COMMAND: samtools sort /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.bam -o /media/vol2/scratch/lcornet/cassava/
NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.bam

STDERR:

[bam_sort_core] merging from 145 files and 1 in-memory blocks...


STDOUT:



COMMAND: samtools index /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.bam

COMMAND: gatk MarkDuplicates --REMOVE_DUPLICATES true -I /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.bam -O /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam -M /dev/null

STDERR:

02:55:30.305 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/media/vol2/home/lcornet/miniconda/envs/polyploidPhasing/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Oct 13 02:55:30 CEST 2020] MarkDuplicates --INPUT /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.bam --OUTPUT /media/vol2/scratch/lcornet/cassava/NPHASE/nphase/TME3/Mapped/shortReads/TME3.sorted.MD.bam --METRICS_FILE /dev/null --REMOVE_DUPLICATES true --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --ADD_PG_TAG_TO_READS true --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Oct 13, 2020 2:55:30 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Tue Oct 13 02:55:30 CEST 2020] Executing as lcornet@node07.durandal on Linux 2.6.32-504.30.3.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_265-b11; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.8.1
INFO    2020-10-13 02:55:30     MarkDuplicates  Start of doWork freeMemory: 2118824592; totalMemory: 2135949312; maxMemory: 28631367680
INFO    2020-10-13 02:55:30     MarkDuplicates  Reading input file and constructing read end information.
INFO    2020-10-13 02:55:30     MarkDuplicates  Will retain up to 103736839 data points before spilling to disk.
INFO    2020-10-13 02:55:37     MarkDuplicates  Read     1,000,000 records.  Elapsed time: 00:00:06s.  Time for last 1,000,000:    6s.  Last read position: Super-Scaffold_4992:4,549,999
INFO    2020-10-13 02:55:38     MarkDuplicates  Tracking 57097 as yet unmatched pairs. 6284 records in RAM.
INFO    2020-10-13 02:55:43     MarkDuplicates  Read     2,000,000 records.  Elapsed time: 00:00:11s.  Time for last 1,000,000:    5s.  Last read position: Super-Scaffold_4992:9,762,240
INFO    2020-10-13 02:55:43     MarkDuplicates  Tracking 138222 as yet unmatched pairs. 12055 records in RAM.
INFO    2020-10-13 02:55:51     MarkDuplicates  Read     3,000,000 records.  Elapsed time: 00:00:20s.  Time for last 1,000,000:    8s.  Last read position: Super-Scaffold_4992:14,635,465
INFO    2020-10-13 02:55:51     MarkDuplicates  Tracking 212288 as yet unmatched pairs. 16625 records in RAM.
[Tue Oct 13 02:55:56 CEST 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.44 minutes.
Runtime.totalMemory()=8846311424
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.samtools.SAMException: /tmp/lcornet/CSPI.603229561431497019.tmp/2643.tmpnot found
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:64)
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:49)
        at htsjdk.samtools.util.ResourceLimitedMap.get(ResourceLimitedMap.java:76)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.getOutputStreamForSequence(CoordinateSortedPairInfoMap.java:180)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:164)
        at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:566)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: java.io.FileNotFoundException: /tmp/lcornet/CSPI.603229561431497019.tmp/2643.tmp (Too many open files)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at htsjdk.samtools.util.FileAppendStreamLRUCache$Functor.makeValue(FileAppendStreamLRUCache.java:61)
        ... 12 more

**Comment by nPhasePipeline** [comment]
This line is saying you have too many files open simultaneously:

`Caused by: java.io.FileNotFoundException: /tmp/lcornet/CSPI.603229561431497019.tmp/2643.tmp (Too many open files)`

Are you perhaps running it through a cluster that has more strict open file number restrictions than when you ran it previously using a singularity?

**Comment by Lcornet** [comment]
Yes it is not the same cluster, a smallest one. I 'll contact the admins .

Thanks for help
